const darkTheme: ITheme = {
  colors: {
    notification: "orange",
    primaryBackground: "#222",
    primaryBorder: "#000",
    primaryButtonBackground: "#666",
    headingBackgroundColor: "none",
    headingTextColor: "#fff",
    primaryButtonText: "#fff",
    primaryText: "white",
    secondaryBackground: "#444",
    secondaryBorder: "#733f1a",
    secondaryButtonBackground: "#75b8fa",
    secondaryButtonText: "white",
    secondaryText: "#aaa",
    tertiaryBackground: "cadetblue",
    tertiaryBorder: "#294647",
    tertiaryButtonBackground: "#666",
    logoBackground: "#222",
    logoColor: "white",
    tertiaryText: "white",
    warnButton: "yellow",
    warnText: "white",
    primaryLink: "#83b0f7",
    secondaryLink: "#f2c166",
    dataHeaderBackground: "#333",
    dataRowBackground: "#444",
    modalBackground: "#555",
    modalText: "#222",
    tableHeaderBackground: "#444",
    tableHeaderFontColor: "#bbb",
    checkboxColor: "#127aa1",
    inputOutline: "#fff",
    inputBackground: "transparent",
    inputText: "#fff",
    inputPlaceholder: "#ccc",
  },
};

export default darkTheme;
