const lightTheme: ITheme = {
  colors: {
    notification: "none",
    primaryBackground: "#fff4e8",
    primaryBorder: "#000",
    headingBackgroundColor: "#000",
    headingTextColor: "#fff",
    primaryButtonBackground: "#444",
    primaryButtonText: "#fff",
    logoBackground: "transparent",
    logoColor: "black",
    primaryText: "#333",
    secondaryBackground: "#cdcdcd",
    secondaryBorder: "#aaa",
    secondaryButtonBackground: "#aaa",
    secondaryButtonText: "white",
    secondaryText: "#444",
    tertiaryBackground: "444",
    tertiaryBorder: "#294647",
    tertiaryText: "#fff",
    tertiaryButtonBackground: "#666",
    warnButton: "yellow",
    warnText: "white",
    dataHeaderBackground: "#ccc",
    dataRowBackground: "#aaa",
    modalBackground: "#fff",
    modalText: "#444",
    primaryLink: "cadetblue",
    secondaryLink: "none",
    tableHeaderBackground: "#34baeb",
    tableHeaderFontColor: "#222",
    checkboxColor: "#666",
  },
};

export default lightTheme;
