import { newShade } from "./utilities";

const themeHelper = (themeFile: ITheme) => {
  return {
    ...{ primaryTextColor: themeFile.colors.primaryText },
    ...{ colors: themeFile.colors },
    container: {
      body: {
        margin: 0,
      },
      pageHeader: {
        width: "100%",
        paddingTop: 2,
        paddingBottom: 2,
        backgroundColor: themeFile.colors.headingBackgroundColor,
        height: 40,
        display: "flex",
        justifyItems: "center",
        justifyContent: "center",
      },
      pageHeaderText: {
        color: themeFile.colors.headingTextColor,
        fontSize: 24,
        paddingLeft: 10,
      },
      row: {
        flexDirection: "row",
      },
      wordDrillRow: {
        flexDirection: "row",
        marginTop: 20,
      },
      col: {
        flexDirection: "column",
      },
      card: {
        flex: 1,
      },
      contentContainer: {
        display: "flex",
        flexBais: "content",
        marginLeft: 10,
        marginRight: 10,
      },
      logo: {
        backgroundColor: themeFile.colors.logoBackground,
        display: "flex",
        width: "100%",
        alignItems: "center",
        justifyItems: "center",
        paddingBottom: 10,
      },
      scrollTable: {
        maxHeight: 450,
        height: 450,
        padding: 5,
        paddingBottom: 30,
      },
      wordDrill: {
        paddingTop: 10,
        display: "flex",
      },
      wordDrillLabel: {
        color: "#aaa",
        fontSize: 16,
        marginRight: 10,
        width: 100,
      },
      wordDrillValue: {
        color: "#fff",
        fontSize: 16,
        width: 250,
      },
      warn: {
        minHeight: 200,
        margin: 20,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        backgroundColor: "#151515",
        justifyContent: "center",
        alignItems: "center",
      },
      screen: {
        flex: 1,
        backgroundColor: themeFile.colors.primaryBackground,
        padding: 0,
        paddingTop: 50,
      },
      screenText: {
        fontSize: 16,
        color: themeFile.colors.primaryText,
        padding: 10,
      },
      colFlexEnd: {
        alignItems: "flex-end",
        justifyContent: "center",
        marginRight: 10,
        marginBottom: 10,
      },
      colFlexStart: {
        alignItems: "flex-start",
        justifyItems: "center",
        marginRight: 10,
        marginBottom: 10,
      },
      settingsColLeft: {
        width: 200,
        alignItems: "flex-end",
        justifyItems: "center",
        marginRight: 10,
        marginBottom: 10,
        height: 50,
        display: "flex",
        justifyContent: "center",
      },
      settingsColRight: {
        alignItems: "flex-start",
        justifyItems: "center",
        marginBottom: 10,
      },
      settingsText: {
        fontSize: 16,
        color: themeFile.colors.primaryText,
      },
      centeredRow: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
      },
      overlay: {
        display: "relative",
        height: 100,
        width: 200,
        top: 5,
        left: 5,
        zIndex: 100,
        backgroundColor: "rgba(0, 0, 0, .9)",
      },
      loader: {
        backgroundColor: themeFile.colors.primaryBackground,
        padding: 10,
        display: "flex",
        alignItems: "center",
      },
      loaderText: {
        color: "#aaa",
        fontSize: 20,
        fontStyle: "italic",
      },
      modal: {
        display: "relative",
        width: "80%",
        left: "10%",
        top: "50%",
        zIndex: 200,
        height: 350,
        backgroundColor: "rgba(155, 155, 0, 1.0)",
        border: "#000",
        borderRadius: 10,
      },
    },
    button: {
      primary: {
        marginTop: 80,
        backgroundColor: themeFile.colors.primaryButtonBackground,
        paddingHorizontal: 140,
        paddingVertical: 10,
        borderRadius: 30,
      },
      play: {
        width: 20,
        backgroundColor: "green",
        margin: 0,
        padding: 0,
        height: 22,
      },
      primaryText: {
        fontSize: 16,
        color: themeFile.colors.primaryButtonText,
      },
      settings: {
        backgroundColor: themeFile.colors.tertiaryButtonBackground,
        borderRadius: 10,
        padding: 5,
        marginRight: 10,
        fontSize: 16,
      },
      settingsText: {
        fontSize: 16,
        color: themeFile.colors.tertiaryText,
      },
      menuText: {
        color: themeFile.colors.primaryText,
        fontSize: 24,
      },
      icon: {
        maxHeight: 32,
        maxWidth: 32,
        width: 32,
        height: 32,
        marginRight: 10,
      },
      nav: {
        maxHeight: 24,
        maxWidth: 24,
        width: 24,
        height: 24,
        marginRight: 10,
      },
      action: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        backgroundColor: themeFile.colors.primaryButtonBackground,
        borderRadius: 8,
        paddingVertical: 10,
      },
      defaultButton: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        borderRadius: 8,
        backgroundColor: themeFile.colors.primaryButtonBackground,
      },
      replace: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        justifySelf: "center",
        alignSelf: "center",
        borderRadius: 8,
        backgroundColor: themeFile.colors.secondaryButtonBackground,
        marginRight: 10,
        paddingLeft: 10,
      },
      defaultButtonPressed: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        borderRadius: 8,
        backgroundColor: "#444",
      },
      menu: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
        minWidth: 300,
        minHeight: 50,
        backgroundColor: themeFile.colors.primaryButtonBackground,
      },
      skip: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
        width: 200,
        backgroundColor: "#2196F3",
      },
      play1: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        borderWidth: 2,
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
        marginTop: 20,
        minWidth: 300,
        minHeight: 50,
      },
      play2: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        backgroundColor: "green",
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
        minWidth: 300,
        minHeight: 50,
      },
      neutral: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        alignContent: "center",
        justifyContent: "center",
        justifyItems: "center",
        borderWidth: 2,
        borderRadius: 8,
        padding: 10,
        marginBottom: 20,
        minWidth: 300,
        minHeight: 50,
      },
      tertiaryButton: {
        backgroundColor: themeFile.colors.tertiaryButtonBackground,
        height: 40,
      },
      tertiaryText: {
        color: themeFile.colors.tertiaryText,
        fontSize: 16,
      },
    },
    text: {
      primaryLink: {
        color: themeFile.colors.primaryLink,
        fontSize: 16,
      },
      pimaryTextColor: {
        color: themeFile.colors.primaryText,
        fontSize: 16,
      },
    },
    dataTable: {
      header: {
        backgroundColor: themeFile.colors.tableHeaderBackground,
        borderBottomWidth: 0,
      },
      headerText: {
        color: themeFile.colors.tableHeaderFontColor,
        fontSize: 16,
      },
      row: {
        borderBottomColor: newShade(themeFile.colors.primaryBackground, 100),
        backgroundColor: newShade(themeFile.colors.primaryBackground, 10),
      },
      rowText: {
        color: themeFile.colors.secondaryText,
        fontSize: 16,
      },
      rowTextLink: {
        color: themeFile.colors.primaryLink,
        fontSize: 16,
      },
    },
  };
};

export default themeHelper;
